//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SanPham", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SanPham : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MSSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSPField;
        
        private double DonGiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MSSP {
            get {
                return this.MSSPField;
            }
            set {
                if ((this.MSSPField.Equals(value) != true)) {
                    this.MSSPField = value;
                    this.RaisePropertyChanged("MSSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenSP {
            get {
                return this.TenSPField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSPField, value) != true)) {
                    this.TenSPField = value;
                    this.RaisePropertyChanged("TenSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double DonGia {
            get {
                return this.DonGiaField;
            }
            set {
                if ((this.DonGiaField.Equals(value) != true)) {
                    this.DonGiaField = value;
                    this.RaisePropertyChanged("DonGia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChiTietDonDatHang", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ChiTietDonDatHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference.SanPham SPField;
        
        private double DonGiaField;
        
        private int SoLuongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ConsoleApplication1.ServiceReference.SanPham SP {
            get {
                return this.SPField;
            }
            set {
                if ((object.ReferenceEquals(this.SPField, value) != true)) {
                    this.SPField = value;
                    this.RaisePropertyChanged("SP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double DonGia {
            get {
                return this.DonGiaField;
            }
            set {
                if ((this.DonGiaField.Equals(value) != true)) {
                    this.DonGiaField = value;
                    this.RaisePropertyChanged("DonGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Add", ReplyAction="*")]
        System.IAsyncResult BeginAdd(int a, int b, System.AsyncCallback callback, object asyncState);
        
        int EndAdd(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Init", ReplyAction="*")]
        void Init();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Init", ReplyAction="*")]
        System.IAsyncResult BeginInit(System.AsyncCallback callback, object asyncState);
        
        void EndInit(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name TenSP from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimSanPhamTheoTen", ReplyAction="*")]
        ConsoleApplication1.ServiceReference.TimSanPhamTheoTenResponse TimSanPhamTheoTen(ConsoleApplication1.ServiceReference.TimSanPhamTheoTenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/TimSanPhamTheoTen", ReplyAction="*")]
        System.IAsyncResult BeginTimSanPhamTheoTen(ConsoleApplication1.ServiceReference.TimSanPhamTheoTenRequest request, System.AsyncCallback callback, object asyncState);
        
        ConsoleApplication1.ServiceReference.TimSanPhamTheoTenResponse EndTimSanPhamTheoTen(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name chitiet from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DatHang", ReplyAction="*")]
        ConsoleApplication1.ServiceReference.DatHangResponse DatHang(ConsoleApplication1.ServiceReference.DatHangRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DatHang", ReplyAction="*")]
        System.IAsyncResult BeginDatHang(ConsoleApplication1.ServiceReference.DatHangRequest request, System.AsyncCallback callback, object asyncState);
        
        ConsoleApplication1.ServiceReference.DatHangResponse EndDatHang(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TongTriGiaDonDatHang", ReplyAction="*")]
        double TongTriGiaDonDatHang(int MSDDH);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/TongTriGiaDonDatHang", ReplyAction="*")]
        System.IAsyncResult BeginTongTriGiaDonDatHang(int MSDDH, System.AsyncCallback callback, object asyncState);
        
        double EndTongTriGiaDonDatHang(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name LayTenSanPhamTheoMSSPResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayTenSanPhamTheoMSSP", ReplyAction="*")]
        ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPResponse LayTenSanPhamTheoMSSP(ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/LayTenSanPhamTheoMSSP", ReplyAction="*")]
        System.IAsyncResult BeginLayTenSanPhamTheoMSSP(ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPRequest request, System.AsyncCallback callback, object asyncState);
        
        ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPResponse EndLayTenSanPhamTheoMSSP(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name TenSP from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CapNhatTenSanPhamTheoMSSP", ReplyAction="*")]
        ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPResponse CapNhatTenSanPhamTheoMSSP(ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/CapNhatTenSanPhamTheoMSSP", ReplyAction="*")]
        System.IAsyncResult BeginCapNhatTenSanPhamTheoMSSP(ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPRequest request, System.AsyncCallback callback, object asyncState);
        
        ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPResponse EndCapNhatTenSanPhamTheoMSSP(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimSanPhamTheoTenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimSanPhamTheoTen", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference.TimSanPhamTheoTenRequestBody Body;
        
        public TimSanPhamTheoTenRequest() {
        }
        
        public TimSanPhamTheoTenRequest(ConsoleApplication1.ServiceReference.TimSanPhamTheoTenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TimSanPhamTheoTenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TenSP;
        
        public TimSanPhamTheoTenRequestBody() {
        }
        
        public TimSanPhamTheoTenRequestBody(string TenSP) {
            this.TenSP = TenSP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimSanPhamTheoTenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimSanPhamTheoTenResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference.TimSanPhamTheoTenResponseBody Body;
        
        public TimSanPhamTheoTenResponse() {
        }
        
        public TimSanPhamTheoTenResponse(ConsoleApplication1.ServiceReference.TimSanPhamTheoTenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TimSanPhamTheoTenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication1.ServiceReference.SanPham[] TimSanPhamTheoTenResult;
        
        public TimSanPhamTheoTenResponseBody() {
        }
        
        public TimSanPhamTheoTenResponseBody(ConsoleApplication1.ServiceReference.SanPham[] TimSanPhamTheoTenResult) {
            this.TimSanPhamTheoTenResult = TimSanPhamTheoTenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DatHangRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DatHang", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference.DatHangRequestBody Body;
        
        public DatHangRequest() {
        }
        
        public DatHangRequest(ConsoleApplication1.ServiceReference.DatHangRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DatHangRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication1.ServiceReference.ChiTietDonDatHang[] chitiet;
        
        public DatHangRequestBody() {
        }
        
        public DatHangRequestBody(ConsoleApplication1.ServiceReference.ChiTietDonDatHang[] chitiet) {
            this.chitiet = chitiet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DatHangResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DatHangResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference.DatHangResponseBody Body;
        
        public DatHangResponse() {
        }
        
        public DatHangResponse(ConsoleApplication1.ServiceReference.DatHangResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DatHangResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DatHangResult;
        
        public DatHangResponseBody() {
        }
        
        public DatHangResponseBody(int DatHangResult) {
            this.DatHangResult = DatHangResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LayTenSanPhamTheoMSSPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LayTenSanPhamTheoMSSP", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPRequestBody Body;
        
        public LayTenSanPhamTheoMSSPRequest() {
        }
        
        public LayTenSanPhamTheoMSSPRequest(ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LayTenSanPhamTheoMSSPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int MSSP;
        
        public LayTenSanPhamTheoMSSPRequestBody() {
        }
        
        public LayTenSanPhamTheoMSSPRequestBody(int MSSP) {
            this.MSSP = MSSP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LayTenSanPhamTheoMSSPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LayTenSanPhamTheoMSSPResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPResponseBody Body;
        
        public LayTenSanPhamTheoMSSPResponse() {
        }
        
        public LayTenSanPhamTheoMSSPResponse(ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LayTenSanPhamTheoMSSPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LayTenSanPhamTheoMSSPResult;
        
        public LayTenSanPhamTheoMSSPResponseBody() {
        }
        
        public LayTenSanPhamTheoMSSPResponseBody(string LayTenSanPhamTheoMSSPResult) {
            this.LayTenSanPhamTheoMSSPResult = LayTenSanPhamTheoMSSPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CapNhatTenSanPhamTheoMSSPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CapNhatTenSanPhamTheoMSSP", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPRequestBody Body;
        
        public CapNhatTenSanPhamTheoMSSPRequest() {
        }
        
        public CapNhatTenSanPhamTheoMSSPRequest(ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CapNhatTenSanPhamTheoMSSPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int MSSP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TenSP;
        
        public CapNhatTenSanPhamTheoMSSPRequestBody() {
        }
        
        public CapNhatTenSanPhamTheoMSSPRequestBody(int MSSP, string TenSP) {
            this.MSSP = MSSP;
            this.TenSP = TenSP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CapNhatTenSanPhamTheoMSSPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CapNhatTenSanPhamTheoMSSPResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPResponseBody Body;
        
        public CapNhatTenSanPhamTheoMSSPResponse() {
        }
        
        public CapNhatTenSanPhamTheoMSSPResponse(ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CapNhatTenSanPhamTheoMSSPResponseBody {
        
        public CapNhatTenSanPhamTheoMSSPResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : ConsoleApplication1.ServiceReference.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimSanPhamTheoTenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TimSanPhamTheoTenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ConsoleApplication1.ServiceReference.SanPham[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ConsoleApplication1.ServiceReference.SanPham[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatHangCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DatHangCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TongTriGiaDonDatHangCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TongTriGiaDonDatHangCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public double Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LayTenSanPhamTheoMSSPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LayTenSanPhamTheoMSSPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference.ServiceSoap>, ConsoleApplication1.ServiceReference.ServiceSoap {
        
        private BeginOperationDelegate onBeginAddDelegate;
        
        private EndOperationDelegate onEndAddDelegate;
        
        private System.Threading.SendOrPostCallback onAddCompletedDelegate;
        
        private BeginOperationDelegate onBeginInitDelegate;
        
        private EndOperationDelegate onEndInitDelegate;
        
        private System.Threading.SendOrPostCallback onInitCompletedDelegate;
        
        private BeginOperationDelegate onBeginTimSanPhamTheoTenDelegate;
        
        private EndOperationDelegate onEndTimSanPhamTheoTenDelegate;
        
        private System.Threading.SendOrPostCallback onTimSanPhamTheoTenCompletedDelegate;
        
        private BeginOperationDelegate onBeginDatHangDelegate;
        
        private EndOperationDelegate onEndDatHangDelegate;
        
        private System.Threading.SendOrPostCallback onDatHangCompletedDelegate;
        
        private BeginOperationDelegate onBeginTongTriGiaDonDatHangDelegate;
        
        private EndOperationDelegate onEndTongTriGiaDonDatHangDelegate;
        
        private System.Threading.SendOrPostCallback onTongTriGiaDonDatHangCompletedDelegate;
        
        private BeginOperationDelegate onBeginLayTenSanPhamTheoMSSPDelegate;
        
        private EndOperationDelegate onEndLayTenSanPhamTheoMSSPDelegate;
        
        private System.Threading.SendOrPostCallback onLayTenSanPhamTheoMSSPCompletedDelegate;
        
        private BeginOperationDelegate onBeginCapNhatTenSanPhamTheoMSSPDelegate;
        
        private EndOperationDelegate onEndCapNhatTenSanPhamTheoMSSPDelegate;
        
        private System.Threading.SendOrPostCallback onCapNhatTenSanPhamTheoMSSPCompletedDelegate;
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<AddCompletedEventArgs> AddCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> InitCompleted;
        
        public event System.EventHandler<TimSanPhamTheoTenCompletedEventArgs> TimSanPhamTheoTenCompleted;
        
        public event System.EventHandler<DatHangCompletedEventArgs> DatHangCompleted;
        
        public event System.EventHandler<TongTriGiaDonDatHangCompletedEventArgs> TongTriGiaDonDatHangCompleted;
        
        public event System.EventHandler<LayTenSanPhamTheoMSSPCompletedEventArgs> LayTenSanPhamTheoMSSPCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CapNhatTenSanPhamTheoMSSPCompleted;
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAdd(int a, int b, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAdd(a, b, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndAdd(System.IAsyncResult result) {
            return base.Channel.EndAdd(result);
        }
        
        private System.IAsyncResult OnBeginAdd(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int a = ((int)(inValues[0]));
            int b = ((int)(inValues[1]));
            return this.BeginAdd(a, b, callback, asyncState);
        }
        
        private object[] OnEndAdd(System.IAsyncResult result) {
            int retVal = this.EndAdd(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddCompleted(object state) {
            if ((this.AddCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddCompleted(this, new AddCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddAsync(int a, int b) {
            this.AddAsync(a, b, null);
        }
        
        public void AddAsync(int a, int b, object userState) {
            if ((this.onBeginAddDelegate == null)) {
                this.onBeginAddDelegate = new BeginOperationDelegate(this.OnBeginAdd);
            }
            if ((this.onEndAddDelegate == null)) {
                this.onEndAddDelegate = new EndOperationDelegate(this.OnEndAdd);
            }
            if ((this.onAddCompletedDelegate == null)) {
                this.onAddCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddCompleted);
            }
            base.InvokeAsync(this.onBeginAddDelegate, new object[] {
                        a,
                        b}, this.onEndAddDelegate, this.onAddCompletedDelegate, userState);
        }
        
        public void Init() {
            base.Channel.Init();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginInit(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInit(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndInit(System.IAsyncResult result) {
            base.Channel.EndInit(result);
        }
        
        private System.IAsyncResult OnBeginInit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginInit(callback, asyncState);
        }
        
        private object[] OnEndInit(System.IAsyncResult result) {
            this.EndInit(result);
            return null;
        }
        
        private void OnInitCompleted(object state) {
            if ((this.InitCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InitCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InitAsync() {
            this.InitAsync(null);
        }
        
        public void InitAsync(object userState) {
            if ((this.onBeginInitDelegate == null)) {
                this.onBeginInitDelegate = new BeginOperationDelegate(this.OnBeginInit);
            }
            if ((this.onEndInitDelegate == null)) {
                this.onEndInitDelegate = new EndOperationDelegate(this.OnEndInit);
            }
            if ((this.onInitCompletedDelegate == null)) {
                this.onInitCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInitCompleted);
            }
            base.InvokeAsync(this.onBeginInitDelegate, null, this.onEndInitDelegate, this.onInitCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.TimSanPhamTheoTenResponse ConsoleApplication1.ServiceReference.ServiceSoap.TimSanPhamTheoTen(ConsoleApplication1.ServiceReference.TimSanPhamTheoTenRequest request) {
            return base.Channel.TimSanPhamTheoTen(request);
        }
        
        public ConsoleApplication1.ServiceReference.SanPham[] TimSanPhamTheoTen(string TenSP) {
            ConsoleApplication1.ServiceReference.TimSanPhamTheoTenRequest inValue = new ConsoleApplication1.ServiceReference.TimSanPhamTheoTenRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference.TimSanPhamTheoTenRequestBody();
            inValue.Body.TenSP = TenSP;
            ConsoleApplication1.ServiceReference.TimSanPhamTheoTenResponse retVal = ((ConsoleApplication1.ServiceReference.ServiceSoap)(this)).TimSanPhamTheoTen(inValue);
            return retVal.Body.TimSanPhamTheoTenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ConsoleApplication1.ServiceReference.ServiceSoap.BeginTimSanPhamTheoTen(ConsoleApplication1.ServiceReference.TimSanPhamTheoTenRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTimSanPhamTheoTen(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginTimSanPhamTheoTen(string TenSP, System.AsyncCallback callback, object asyncState) {
            ConsoleApplication1.ServiceReference.TimSanPhamTheoTenRequest inValue = new ConsoleApplication1.ServiceReference.TimSanPhamTheoTenRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference.TimSanPhamTheoTenRequestBody();
            inValue.Body.TenSP = TenSP;
            return ((ConsoleApplication1.ServiceReference.ServiceSoap)(this)).BeginTimSanPhamTheoTen(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.TimSanPhamTheoTenResponse ConsoleApplication1.ServiceReference.ServiceSoap.EndTimSanPhamTheoTen(System.IAsyncResult result) {
            return base.Channel.EndTimSanPhamTheoTen(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ConsoleApplication1.ServiceReference.SanPham[] EndTimSanPhamTheoTen(System.IAsyncResult result) {
            ConsoleApplication1.ServiceReference.TimSanPhamTheoTenResponse retVal = ((ConsoleApplication1.ServiceReference.ServiceSoap)(this)).EndTimSanPhamTheoTen(result);
            return retVal.Body.TimSanPhamTheoTenResult;
        }
        
        private System.IAsyncResult OnBeginTimSanPhamTheoTen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string TenSP = ((string)(inValues[0]));
            return this.BeginTimSanPhamTheoTen(TenSP, callback, asyncState);
        }
        
        private object[] OnEndTimSanPhamTheoTen(System.IAsyncResult result) {
            ConsoleApplication1.ServiceReference.SanPham[] retVal = this.EndTimSanPhamTheoTen(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTimSanPhamTheoTenCompleted(object state) {
            if ((this.TimSanPhamTheoTenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TimSanPhamTheoTenCompleted(this, new TimSanPhamTheoTenCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TimSanPhamTheoTenAsync(string TenSP) {
            this.TimSanPhamTheoTenAsync(TenSP, null);
        }
        
        public void TimSanPhamTheoTenAsync(string TenSP, object userState) {
            if ((this.onBeginTimSanPhamTheoTenDelegate == null)) {
                this.onBeginTimSanPhamTheoTenDelegate = new BeginOperationDelegate(this.OnBeginTimSanPhamTheoTen);
            }
            if ((this.onEndTimSanPhamTheoTenDelegate == null)) {
                this.onEndTimSanPhamTheoTenDelegate = new EndOperationDelegate(this.OnEndTimSanPhamTheoTen);
            }
            if ((this.onTimSanPhamTheoTenCompletedDelegate == null)) {
                this.onTimSanPhamTheoTenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTimSanPhamTheoTenCompleted);
            }
            base.InvokeAsync(this.onBeginTimSanPhamTheoTenDelegate, new object[] {
                        TenSP}, this.onEndTimSanPhamTheoTenDelegate, this.onTimSanPhamTheoTenCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.DatHangResponse ConsoleApplication1.ServiceReference.ServiceSoap.DatHang(ConsoleApplication1.ServiceReference.DatHangRequest request) {
            return base.Channel.DatHang(request);
        }
        
        public int DatHang(ConsoleApplication1.ServiceReference.ChiTietDonDatHang[] chitiet) {
            ConsoleApplication1.ServiceReference.DatHangRequest inValue = new ConsoleApplication1.ServiceReference.DatHangRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference.DatHangRequestBody();
            inValue.Body.chitiet = chitiet;
            ConsoleApplication1.ServiceReference.DatHangResponse retVal = ((ConsoleApplication1.ServiceReference.ServiceSoap)(this)).DatHang(inValue);
            return retVal.Body.DatHangResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ConsoleApplication1.ServiceReference.ServiceSoap.BeginDatHang(ConsoleApplication1.ServiceReference.DatHangRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDatHang(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDatHang(ConsoleApplication1.ServiceReference.ChiTietDonDatHang[] chitiet, System.AsyncCallback callback, object asyncState) {
            ConsoleApplication1.ServiceReference.DatHangRequest inValue = new ConsoleApplication1.ServiceReference.DatHangRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference.DatHangRequestBody();
            inValue.Body.chitiet = chitiet;
            return ((ConsoleApplication1.ServiceReference.ServiceSoap)(this)).BeginDatHang(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.DatHangResponse ConsoleApplication1.ServiceReference.ServiceSoap.EndDatHang(System.IAsyncResult result) {
            return base.Channel.EndDatHang(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndDatHang(System.IAsyncResult result) {
            ConsoleApplication1.ServiceReference.DatHangResponse retVal = ((ConsoleApplication1.ServiceReference.ServiceSoap)(this)).EndDatHang(result);
            return retVal.Body.DatHangResult;
        }
        
        private System.IAsyncResult OnBeginDatHang(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ConsoleApplication1.ServiceReference.ChiTietDonDatHang[] chitiet = ((ConsoleApplication1.ServiceReference.ChiTietDonDatHang[])(inValues[0]));
            return this.BeginDatHang(chitiet, callback, asyncState);
        }
        
        private object[] OnEndDatHang(System.IAsyncResult result) {
            int retVal = this.EndDatHang(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDatHangCompleted(object state) {
            if ((this.DatHangCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DatHangCompleted(this, new DatHangCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DatHangAsync(ConsoleApplication1.ServiceReference.ChiTietDonDatHang[] chitiet) {
            this.DatHangAsync(chitiet, null);
        }
        
        public void DatHangAsync(ConsoleApplication1.ServiceReference.ChiTietDonDatHang[] chitiet, object userState) {
            if ((this.onBeginDatHangDelegate == null)) {
                this.onBeginDatHangDelegate = new BeginOperationDelegate(this.OnBeginDatHang);
            }
            if ((this.onEndDatHangDelegate == null)) {
                this.onEndDatHangDelegate = new EndOperationDelegate(this.OnEndDatHang);
            }
            if ((this.onDatHangCompletedDelegate == null)) {
                this.onDatHangCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDatHangCompleted);
            }
            base.InvokeAsync(this.onBeginDatHangDelegate, new object[] {
                        chitiet}, this.onEndDatHangDelegate, this.onDatHangCompletedDelegate, userState);
        }
        
        public double TongTriGiaDonDatHang(int MSDDH) {
            return base.Channel.TongTriGiaDonDatHang(MSDDH);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginTongTriGiaDonDatHang(int MSDDH, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTongTriGiaDonDatHang(MSDDH, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public double EndTongTriGiaDonDatHang(System.IAsyncResult result) {
            return base.Channel.EndTongTriGiaDonDatHang(result);
        }
        
        private System.IAsyncResult OnBeginTongTriGiaDonDatHang(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int MSDDH = ((int)(inValues[0]));
            return this.BeginTongTriGiaDonDatHang(MSDDH, callback, asyncState);
        }
        
        private object[] OnEndTongTriGiaDonDatHang(System.IAsyncResult result) {
            double retVal = this.EndTongTriGiaDonDatHang(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTongTriGiaDonDatHangCompleted(object state) {
            if ((this.TongTriGiaDonDatHangCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TongTriGiaDonDatHangCompleted(this, new TongTriGiaDonDatHangCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TongTriGiaDonDatHangAsync(int MSDDH) {
            this.TongTriGiaDonDatHangAsync(MSDDH, null);
        }
        
        public void TongTriGiaDonDatHangAsync(int MSDDH, object userState) {
            if ((this.onBeginTongTriGiaDonDatHangDelegate == null)) {
                this.onBeginTongTriGiaDonDatHangDelegate = new BeginOperationDelegate(this.OnBeginTongTriGiaDonDatHang);
            }
            if ((this.onEndTongTriGiaDonDatHangDelegate == null)) {
                this.onEndTongTriGiaDonDatHangDelegate = new EndOperationDelegate(this.OnEndTongTriGiaDonDatHang);
            }
            if ((this.onTongTriGiaDonDatHangCompletedDelegate == null)) {
                this.onTongTriGiaDonDatHangCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTongTriGiaDonDatHangCompleted);
            }
            base.InvokeAsync(this.onBeginTongTriGiaDonDatHangDelegate, new object[] {
                        MSDDH}, this.onEndTongTriGiaDonDatHangDelegate, this.onTongTriGiaDonDatHangCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPResponse ConsoleApplication1.ServiceReference.ServiceSoap.LayTenSanPhamTheoMSSP(ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPRequest request) {
            return base.Channel.LayTenSanPhamTheoMSSP(request);
        }
        
        public string LayTenSanPhamTheoMSSP(int MSSP) {
            ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPRequest inValue = new ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPRequestBody();
            inValue.Body.MSSP = MSSP;
            ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPResponse retVal = ((ConsoleApplication1.ServiceReference.ServiceSoap)(this)).LayTenSanPhamTheoMSSP(inValue);
            return retVal.Body.LayTenSanPhamTheoMSSPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ConsoleApplication1.ServiceReference.ServiceSoap.BeginLayTenSanPhamTheoMSSP(ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLayTenSanPhamTheoMSSP(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginLayTenSanPhamTheoMSSP(int MSSP, System.AsyncCallback callback, object asyncState) {
            ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPRequest inValue = new ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPRequestBody();
            inValue.Body.MSSP = MSSP;
            return ((ConsoleApplication1.ServiceReference.ServiceSoap)(this)).BeginLayTenSanPhamTheoMSSP(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPResponse ConsoleApplication1.ServiceReference.ServiceSoap.EndLayTenSanPhamTheoMSSP(System.IAsyncResult result) {
            return base.Channel.EndLayTenSanPhamTheoMSSP(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndLayTenSanPhamTheoMSSP(System.IAsyncResult result) {
            ConsoleApplication1.ServiceReference.LayTenSanPhamTheoMSSPResponse retVal = ((ConsoleApplication1.ServiceReference.ServiceSoap)(this)).EndLayTenSanPhamTheoMSSP(result);
            return retVal.Body.LayTenSanPhamTheoMSSPResult;
        }
        
        private System.IAsyncResult OnBeginLayTenSanPhamTheoMSSP(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int MSSP = ((int)(inValues[0]));
            return this.BeginLayTenSanPhamTheoMSSP(MSSP, callback, asyncState);
        }
        
        private object[] OnEndLayTenSanPhamTheoMSSP(System.IAsyncResult result) {
            string retVal = this.EndLayTenSanPhamTheoMSSP(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLayTenSanPhamTheoMSSPCompleted(object state) {
            if ((this.LayTenSanPhamTheoMSSPCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LayTenSanPhamTheoMSSPCompleted(this, new LayTenSanPhamTheoMSSPCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LayTenSanPhamTheoMSSPAsync(int MSSP) {
            this.LayTenSanPhamTheoMSSPAsync(MSSP, null);
        }
        
        public void LayTenSanPhamTheoMSSPAsync(int MSSP, object userState) {
            if ((this.onBeginLayTenSanPhamTheoMSSPDelegate == null)) {
                this.onBeginLayTenSanPhamTheoMSSPDelegate = new BeginOperationDelegate(this.OnBeginLayTenSanPhamTheoMSSP);
            }
            if ((this.onEndLayTenSanPhamTheoMSSPDelegate == null)) {
                this.onEndLayTenSanPhamTheoMSSPDelegate = new EndOperationDelegate(this.OnEndLayTenSanPhamTheoMSSP);
            }
            if ((this.onLayTenSanPhamTheoMSSPCompletedDelegate == null)) {
                this.onLayTenSanPhamTheoMSSPCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLayTenSanPhamTheoMSSPCompleted);
            }
            base.InvokeAsync(this.onBeginLayTenSanPhamTheoMSSPDelegate, new object[] {
                        MSSP}, this.onEndLayTenSanPhamTheoMSSPDelegate, this.onLayTenSanPhamTheoMSSPCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPResponse ConsoleApplication1.ServiceReference.ServiceSoap.CapNhatTenSanPhamTheoMSSP(ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPRequest request) {
            return base.Channel.CapNhatTenSanPhamTheoMSSP(request);
        }
        
        public void CapNhatTenSanPhamTheoMSSP(int MSSP, string TenSP) {
            ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPRequest inValue = new ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPRequestBody();
            inValue.Body.MSSP = MSSP;
            inValue.Body.TenSP = TenSP;
            ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPResponse retVal = ((ConsoleApplication1.ServiceReference.ServiceSoap)(this)).CapNhatTenSanPhamTheoMSSP(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ConsoleApplication1.ServiceReference.ServiceSoap.BeginCapNhatTenSanPhamTheoMSSP(ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCapNhatTenSanPhamTheoMSSP(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCapNhatTenSanPhamTheoMSSP(int MSSP, string TenSP, System.AsyncCallback callback, object asyncState) {
            ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPRequest inValue = new ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPRequestBody();
            inValue.Body.MSSP = MSSP;
            inValue.Body.TenSP = TenSP;
            return ((ConsoleApplication1.ServiceReference.ServiceSoap)(this)).BeginCapNhatTenSanPhamTheoMSSP(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPResponse ConsoleApplication1.ServiceReference.ServiceSoap.EndCapNhatTenSanPhamTheoMSSP(System.IAsyncResult result) {
            return base.Channel.EndCapNhatTenSanPhamTheoMSSP(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndCapNhatTenSanPhamTheoMSSP(System.IAsyncResult result) {
            ConsoleApplication1.ServiceReference.CapNhatTenSanPhamTheoMSSPResponse retVal = ((ConsoleApplication1.ServiceReference.ServiceSoap)(this)).EndCapNhatTenSanPhamTheoMSSP(result);
        }
        
        private System.IAsyncResult OnBeginCapNhatTenSanPhamTheoMSSP(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int MSSP = ((int)(inValues[0]));
            string TenSP = ((string)(inValues[1]));
            return this.BeginCapNhatTenSanPhamTheoMSSP(MSSP, TenSP, callback, asyncState);
        }
        
        private object[] OnEndCapNhatTenSanPhamTheoMSSP(System.IAsyncResult result) {
            this.EndCapNhatTenSanPhamTheoMSSP(result);
            return null;
        }
        
        private void OnCapNhatTenSanPhamTheoMSSPCompleted(object state) {
            if ((this.CapNhatTenSanPhamTheoMSSPCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CapNhatTenSanPhamTheoMSSPCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CapNhatTenSanPhamTheoMSSPAsync(int MSSP, string TenSP) {
            this.CapNhatTenSanPhamTheoMSSPAsync(MSSP, TenSP, null);
        }
        
        public void CapNhatTenSanPhamTheoMSSPAsync(int MSSP, string TenSP, object userState) {
            if ((this.onBeginCapNhatTenSanPhamTheoMSSPDelegate == null)) {
                this.onBeginCapNhatTenSanPhamTheoMSSPDelegate = new BeginOperationDelegate(this.OnBeginCapNhatTenSanPhamTheoMSSP);
            }
            if ((this.onEndCapNhatTenSanPhamTheoMSSPDelegate == null)) {
                this.onEndCapNhatTenSanPhamTheoMSSPDelegate = new EndOperationDelegate(this.OnEndCapNhatTenSanPhamTheoMSSP);
            }
            if ((this.onCapNhatTenSanPhamTheoMSSPCompletedDelegate == null)) {
                this.onCapNhatTenSanPhamTheoMSSPCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCapNhatTenSanPhamTheoMSSPCompleted);
            }
            base.InvokeAsync(this.onBeginCapNhatTenSanPhamTheoMSSPDelegate, new object[] {
                        MSSP,
                        TenSP}, this.onEndCapNhatTenSanPhamTheoMSSPDelegate, this.onCapNhatTenSanPhamTheoMSSPCompletedDelegate, userState);
        }
    }
}
